version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: triage_db_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: triage_db
    ports:
      - "5433:5432"
    volumes:
      - fluxtriage_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  fluxtriage_postgres_data:
    driver: local
